### ISSUE TITLE
Using this code

### ISSUE THREAD

**Issue by hbarovertwo** [asoomar/car-design-generation#1]
How can I use this repo to reproduce the results detailed in your article? Great work!

**Comment by asoomar** [comment]
Thanks so much! We have created a readme that should help explain how to use our code for generating new images. In short, you can use `CarGan128_SELU.py` to start you off. The comments have instructions depending on what you want to do.

**Comment by hbarovertwo** [comment]
Sorry to bother you! I finally got your code running on a subset of your dataset. I am wondering one thing, in the CarGan128_SELU.py, when I specify where my training images are stored - do I give the script the raw images and it resizes them etc for me? Or should I resize the images, flip, crop etc before feeding them to the script? I only downloaded the raw images and didn't do any preprocessing. Thank you again!!

**Comment by asoomar** [comment]
If the raw images are all squares, you should be okay. However, if they’re not, it may be unpredictable, as the aspect ratios of the images may be altered. To preprocess the data, I would look into PIL. You can see how we preprocessed our data in data_processing/finalDataProcessing.ipynb Specifically, take a look at functions save_carmax and save_carvana. Depending on the source of the image, we cropped the image a little and added black bars to the top and bottom to make it square. You may want to do something else to process your images, but this is just an example of what we did.
